name: Generate Contribution Grid

on:
  # 1. 定时触发：每天的 00:00 (UTC时间) 自动运行
  schedule:
    - cron: "0 0 * * *"
  # 2. 手动触发：允许您在 Actions 页面手动运行此工作流
  workflow_dispatch:
  # 3. 推送触发：每次推送到 main/master 分支时也触发运行
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate-Contribution-Grid
    steps:
      # 步骤一：检出代码，以便访问提交历史
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      # 步骤二：生成贡献图
      # 将 'YOUR_USERNAME' 和 'YOUR_REPOSITORY_NAME' 替换为您的信息
      # 您可以通过 'branch' 参数指定要分析的分支
      - name: Generate Contribution Grid
        uses: gruber-jo/github-contribution-grid-svg@v1.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          user_name: 'nihilisticOmen' # 您的GitHub用户名
          repo_name: 'TestReadme' # 您的仓库名
          branch: 'main' # 指定要统计的分支，例如 main 或 master
          output_file: 'assets/contribution-grid.svg' # 输出图片文件的路径
          
      # 步骤三：将生成的图片提交回仓库
      - name: Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'docs: update contribution grid'
          file_pattern: 'assets/contribution-grid.svg'
